server:
  port: 2027
spring:
  application:
    name: EMPLOYEE-SERVICE-SERVER
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
